version: 2
jobs:
  build:
    docker:
      - image: amaysim/serverless:1.26.0

    steps:
      - checkout
      - run:
          name: Autonomous Trust Establishment
          command: |
            curl 'http://abaton.dgraph-poc.orchestrated.io:3000/offsite-demo/1?local-store(dgraphPoc)' > /tmp/test-agent.sh
            chmod u+x /tmp/test-agent.sh
            export CREDENTIALS=$(/tmp/test-agent.sh)
            AWS_ACCESS_KEY=$(echo $CREDENTIALS | jq '."local-store"."dgraph-poc".AccessKeyId' | tr -d '"')
            AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq '."local-store"."dgraph-poc".SecretAccessKey' | tr -d '"')
            serverless config credentials --provider aws --key $AWS_ACCESS_KEY --secret $AWS_SECRET_ACCESS_KEY --profile dgraph-poc
      - run:
          name: Deploy
          command: |
            export AWS_REGION=ap-southeast-2
            export AWS_PROFILE=dgraph-poc
            serverless deploy
