version: 2
jobs:
  build:
    docker:
      - image: amaysim/serverless:1.26.0

    steps:
      - checkout
      - run:
          name: Install LastPass CLI
          command: |
            apt-get --no-install-recommends -yqq install \
              bash-completion \
              build-essential \
              cmake \
              libcurl3  \
              libcurl3-openssl-dev  \
              libssl1.0 \
              libssl1.0-dev \
              libxml2 \
              libxml2-dev  \
              pkg-config \
              ca-certificates \
              xclip
            mkdir lpass
            cd lpass
            curl https://github.com/lastpass/lastpass-cli/archive/master.zip > lpass.zip
            unzip lpass.zip
            make
            make install
            echo "LastPass CLI Version: " $(lpass --version)
      - run:
          name: Get AWS Credentials from 1password
          command: |
            echo "echo $OpPwd >" lpassLogin.sh
            chmox u+x lpassLogin.sh
            export LPASS_ASKPASS=./lpassLogin.sh
            eval $(lpass login $OpEmail)
            rm lpassLogin.sh
            export CREDENTIALS=$(lpass show "Orchestrated POC account")
            AWS_ACCESS_KEY=$(echo $CREDENTIALS | grep Username | cut -d ' ' -f 2)
            AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | grep Password | cut -d ' ' -f 2)
            serverless config credentials --provider aws --key $AWS_ACCESS_KEY --secret $AWS_SECRET_ACCESS_KEY --profile dgraph-poc
      - run:
          name: Deploy
          command: |
            export AWS_REGION=ap-southeast-2
            export AWS_PROFILE=dgraph-poc
            serverless deploy
