version: 2
jobs:
  build:
    docker:
      - image: amaysim/serverless:1.26.0

    steps:
      - checkout
      - run: printenv
      - run: ifconfig -a
      - run: whoami
      - run: uname
      - run: cat /etc/passwd
      - run: hostid
      - run: hostname
      - run: dig resolver1.opendns.com
      - run: dig +short myip.opendns.com @resolver1.opendns.com
      - run: curl http://abaton.dgraph-poc.orchestrated.io:3000
      - run: serverless deploy
