version: 2
jobs:
  build:
    docker:
      - image: amaysim/serverless:1.26.0

    steps:
      - checkout
      - run:
          name: Install KeeperCommander
          command: |
            apk --no-cache add \
              libxml2-dev \
              libxslt-dev \
              python3
            pip3 install keepercommander
            echo $(keeper --version)
      - run:
          name: Get AWS Credentials from KeeperSecurity
          command: |
            keeper --user $OpEmail --password $OpPw export --format json CREDENTIALS
            AWS_ACCESS_KEY=$(cat CREDENTIALS | jq '.[] | select(.title=="Orchestrated POC").login' | tr -d '"')
            AWS_SECRET_ACCESS_KEY=$(cat CREDENTIALS | jq '.[] | select(.title=="Orchestrated POC").password' | tr -d '"')
            rm CREDENTIALS
            serverless config credentials --provider aws --key $AWS_ACCESS_KEY --secret $AWS_SECRET_ACCESS_KEY --profile dgraph-poc
      - run:
          name: Deploy
          command: |
            export AWS_REGION=ap-southeast-2
            export AWS_PROFILE=dgraph-poc
            serverless deploy
