version: 2
jobs:
  build:
    docker:
      - image: amaysim/serverless:1.26.0

    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            export AWS_REGION=ap-southeast-2
            export AWS_PROFILE=dgraph-poc
            serverless deploy
